# Generated by Django 4.2.16 on 2024-12-09 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.image_settings.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="create date"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modify date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("title", models.CharField(max_length=255)),
                ("website_url", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "logo",
                    models.ImageField(
                        default="default/website.png",
                        upload_to=home.image_settings.tools.UploadToPathAndRename(
                            "home/"
                        ),
                    ),
                ),
                ("linkedin", models.CharField(blank=True, max_length=200, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=200, null=True)),
                ("instagram", models.CharField(blank=True, max_length=200, null=True)),
                ("telegram", models.CharField(blank=True, max_length=200, null=True)),
                ("creationTime", models.DateTimeField(auto_now_add=True)),
                ("modificationTime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CompanyWebsite",
                "verbose_name_plural": "CompanyWebsite",
                "db_table": "CompanyWebsite",
                "ordering": ["creationTime"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "creationTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "modificationTime",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified"),
                ),
            ],
            options={
                "verbose_name": "OrganizationURL",
                "verbose_name_plural": "OrganizationURL",
                "db_table": "OrganizationURL",
                "ordering": ["creationTime"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="create date"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modify date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Full Name")),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                (
                    "image",
                    models.ImageField(
                        default="default/StaffMember.png",
                        upload_to=home.image_settings.tools.UploadToPathAndRename(
                            "home/"
                        ),
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Birthday")),
                ("active", models.BooleanField(default=False)),
                ("creationTime", models.DateTimeField(auto_now_add=True)),
                ("modificationTime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "StaffMember",
                "verbose_name_plural": "StaffMember",
                "db_table": "StaffMember",
                "ordering": ["creationTime"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("download_link", models.URLField()),
                ("creationTime", models.DateTimeField(auto_now_add=True)),
                ("modificationTime", models.DateTimeField(auto_now=True)),
                (
                    "sv",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.companywebsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "SoftwareVersion",
                "verbose_name_plural": "SoftwareVersion",
                "db_table": "SoftwareVersion",
                "ordering": ["creationTime"],
            },
        ),
        migrations.CreateModel(
            name="SlideShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="create date"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modify date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/slides.png",
                        upload_to=home.image_settings.tools.UploadToPathAndRename(
                            "home/"
                        ),
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "creationTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "modificationTime",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified"),
                ),
                (
                    "company_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="home.companywebsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "SlideShow",
                "verbose_name_plural": "SlideShows",
                "db_table": "SlideShow",
                "ordering": ["creationTime"],
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="create date"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modify date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/article.png",
                        null=True,
                        upload_to=home.image_settings.tools.UploadToPathAndRename(
                            "home/"
                        ),
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("published_date", models.DateTimeField()),
                ("creationTime", models.DateTimeField(auto_now_add=True)),
                ("modificationTime", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NewsArticle",
                "verbose_name_plural": "NewsArticle",
                "db_table": "NewsArticle",
                "ordering": ["creationTime"],
            },
        ),
    ]
