# Generated by Django 4.2.16 on 2024-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwareversion",
            name="software_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/software/"
            ),
        ),
    ]
