# Generated by Django 4.2.16 on 2024-12-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_softwareversion_download_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwareversion",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
